---
name: Number-Interval
version: 0.05
author:
  - 'Tim Jenness <tjenness@cpan.org>'
abstract: Representation of a numeric interval
license: gpl
resources:
  homepage: http://github.com/timj/perl-Number-Interval/tree/master
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/timj/perl-Number-Interval.git
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.3306
generated_by: Module::Build version 0.3306
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
