---
name: Number-Interval
version: 0.05
author:
  - 'Tim X. Jenness <t.jenness@jach.hawaii.edu>'
abstract: Representation of a numeric interval
license: gpl
resources:
  homepage: http://github.com/timj/perl-Number-Interval/tree/master
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
  repository: git://github.com/timj/perl-Number-Interval.git
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
