---
abstract: 'Representation of a numeric interval'
author:
  - 'Tim Jenness <tjenness@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Interval
provides:
  Number::Interval:
    file: lib/Number/Interval.pm
    version: 0.07
resources:
  homepage: http://github.com/timj/perl-Number-Interval/tree/master
  license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
  repository: git://github.com/timj/perl-Number-Interval.git
version: 0.07
